'use client';

import { useState } from 'react';
import { Check, Loader2, Plus, Trash2, X } from 'lucide-react';

type Availability = { id:string; starts_at:string; ends_at:string; status:string; reason:string|null; source:string };
type CastingInvite = { id:string; castingId:string; title:string; startsAt:string|null; location:string|null; stage:string };

export default function ModelAgencyPortal({ initialAvailability, initialCastings }: { initialAvailability:Availability[]; initialCastings:CastingInvite[] }) {
  const [availability,setAvailability] = useState(initialAvailability); const [castings,setCastings] = useState(initialCastings); const [busy,setBusy] = useState(''); const [error,setError] = useState('');
  const [form,setForm] = useState({ startsAt:'', endsAt:'', status:'unavailable', reason:'' });
  const addAvailability = async (event:React.FormEvent) => { event.preventDefault(); setBusy('availability'); setError(''); try { const response=await fetch('/api/model/availability',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)}); const result=await response.json().catch(()=>({})); if(!response.ok) throw new Error(result.error||'Enregistrement impossible.'); setAvailability((rows)=>[result.data,...rows]); setForm({startsAt:'',endsAt:'',status:'unavailable',reason:''}); } catch(cause){setError(cause instanceof Error?cause.message:'Enregistrement impossible.');} finally{setBusy('');} };
  const removeAvailability = async (row:Availability) => { setBusy(row.id); setError(''); try { const response=await fetch(`/api/model/availability?id=${encodeURIComponent(row.id)}`,{method:'DELETE',credentials:'include'}); const result=await response.json().catch(()=>({})); if(!response.ok) throw new Error(result.error||'Suppression impossible.'); setAvailability((rows)=>rows.filter((item)=>item.id!==row.id)); } catch(cause){setError(cause instanceof Error?cause.message:'Suppression impossible.');} finally{setBusy('');} };
  const respond = async (invite:CastingInvite,responseValue:'confirmed'|'declined') => { setBusy(invite.id); setError(''); try { const response=await fetch(`/api/model/castings/${encodeURIComponent(invite.id)}/respond`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({response:responseValue})}); const result=await response.json().catch(()=>({})); if(!response.ok) throw new Error(result.error||'Réponse impossible.'); setCastings((rows)=>rows.map((item)=>item.id===invite.id?{...item,stage:responseValue}:item)); } catch(cause){setError(cause instanceof Error?cause.message:'Réponse impossible.');} finally{setBusy('');} };
  const field='min-h-11 w-full rounded-xl border border-pm-ink/15 bg-white px-3 text-sm outline-none focus:border-pm-coral focus:ring-4 focus:ring-pm-coral/10';
  return <div className="space-y-6">{error&&<p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-semibold text-red-800">{error}</p>}
    <section className="rounded-[1.7rem] border border-pm-ink/10 bg-white p-5 sm:p-6"><div><p className="editorial-kicker text-pm-coral">Mes disponibilités</p><h2 className="mt-2 font-playfair text-3xl font-bold">Informer l’agence</h2><p className="mt-2 text-sm leading-6 text-pm-ink/50">Ajoutez vos périodes d’indisponibilité, voyages ou disponibilités particulières. Elles sont prises en compte dans le matching casting.</p></div><form onSubmit={addAvailability} className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-5"><label><span className="mb-1.5 block text-xs font-bold">Début</span><input required type="datetime-local" value={form.startsAt} onChange={(e)=>setForm({...form,startsAt:e.target.value})} className={field}/></label><label><span className="mb-1.5 block text-xs font-bold">Fin</span><input required type="datetime-local" min={form.startsAt||undefined} value={form.endsAt} onChange={(e)=>setForm({...form,endsAt:e.target.value})} className={field}/></label><label><span className="mb-1.5 block text-xs font-bold">Statut</span><select value={form.status} onChange={(e)=>setForm({...form,status:e.target.value})} className={field}><option value="unavailable">Indisponible</option><option value="travel">Voyage</option><option value="available">Disponible</option><option value="tentative">À confirmer</option></select></label><label><span className="mb-1.5 block text-xs font-bold">Précision</span><input value={form.reason} onChange={(e)=>setForm({...form,reason:e.target.value})} className={field} placeholder="Facultatif"/></label><button disabled={busy==='availability'} className="mt-auto inline-flex min-h-11 items-center justify-center gap-2 rounded-full bg-pm-ink px-5 text-xs font-black uppercase tracking-[.08em] text-white disabled:opacity-50">{busy==='availability'?<Loader2 size={15} className="animate-spin"/>:<Plus size={15}/>} Ajouter</button></form><div className="mt-5 grid gap-2">{availability.map((row)=><div key={row.id} className="flex flex-wrap items-center gap-3 rounded-xl bg-pm-ivory p-3"><span className="rounded-full bg-white px-2.5 py-1 text-[9px] font-black uppercase text-pm-wine">{row.status}</span><span className="flex-1 text-sm"><b>{new Date(row.starts_at).toLocaleString('fr-FR')}</b> → {new Date(row.ends_at).toLocaleString('fr-FR')} {row.reason?`· ${row.reason}`:''}</span>{row.source==='model'&&<button type="button" disabled={busy===row.id} onClick={()=>void removeAvailability(row)} aria-label="Supprimer cette disponibilité" className="grid h-9 w-9 place-items-center rounded-full text-red-600 hover:bg-red-50">{busy===row.id?<Loader2 size={14} className="animate-spin"/>:<Trash2 size={14}/>}</button>}</div>)}{!availability.length&&<p className="rounded-xl bg-pm-ivory p-4 text-sm text-pm-ink/45">Aucune disponibilité particulière renseignée.</p>}</div></section>
    <section className="rounded-[1.7rem] border border-pm-ink/10 bg-white p-5 sm:p-6"><p className="editorial-kicker text-pm-coral">Castings</p><h2 className="mt-2 font-playfair text-3xl font-bold">Mes invitations</h2><div className="mt-5 grid gap-3">{castings.map((invite)=><article key={invite.id} className="grid gap-4 rounded-2xl bg-pm-ivory p-4 md:grid-cols-[1fr_auto] md:items-center"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-playfair text-2xl font-bold">{invite.title}</h3><span className="rounded-full bg-white px-2.5 py-1 text-[9px] font-black uppercase text-pm-wine">{invite.stage}</span></div><p className="mt-2 text-sm text-pm-ink/50">{[invite.startsAt?new Date(invite.startsAt).toLocaleString('fr-FR'):'',invite.location].filter(Boolean).join(' · ')}</p></div>{['invited','confirmed','declined'].includes(invite.stage)&&<div className="flex gap-2"><button disabled={busy===invite.id} onClick={()=>void respond(invite,'confirmed')} className="inline-flex min-h-10 items-center gap-2 rounded-full bg-emerald-700 px-4 text-xs font-black uppercase text-white"><Check size={14}/> Accepter</button><button disabled={busy===invite.id} onClick={()=>void respond(invite,'declined')} className="inline-flex min-h-10 items-center gap-2 rounded-full border border-red-200 bg-white px-4 text-xs font-black uppercase text-red-700"><X size={14}/> Refuser</button></div>}</article>)}{!castings.length&&<p className="rounded-xl bg-pm-ivory p-4 text-sm text-pm-ink/45">Aucune invitation casting actuellement.</p>}</div></section>
  </div>;
}
