'use client';
import React,{createContext,useCallback,useContext,useEffect,useState}from'react';
import { authClient } from '@/lib/auth/client';
import type { UserPermissions } from '../types';
export type UserRole='admin'|'student'|'jury'|'registration'|'jury-contest';
export interface AuthUser{uid:string;email:string|null;displayName:string|null;role:UserRole;userId:string;contestId?:string;permissions?:UserPermissions;mustChangePassword?:boolean;identifier?:string}
export interface ModelMigrationRequest{modelId:string;name:string;suggestedEmail:string}
export interface LoginResult{success:boolean;error?:string;migrationRequired?:boolean;migration?:ModelMigrationRequest}
interface AuthContextType{user:AuthUser|null;loading:boolean;login:(identifier:string,password:string)=>Promise<LoginResult>;logout:()=>Promise<void>;createUserWithRole:(email:string,password:string,role:UserRole,profileData:{id:string;name:string;[key:string]:any})=>Promise<{success:boolean;error?:string}>;migrateModelToAuth:(modelId:string,email:string,newPassword:string,legacyPassword?:string)=>Promise<{success:boolean;error?:string}>;resetPassword:(email:string)=>Promise<{success:boolean;error?:string}>;signInWithPhone:(phone:string,containerId?:string)=>Promise<{success:boolean;error?:string}>;confirmPhoneCode:(code:string)=>Promise<{success:boolean;error?:string}>}
const AuthContext=createContext<AuthContextType|null>(null);export const useAuth=()=>{const c=useContext(AuthContext);if(!c)throw new Error('useAuth must be used within AuthProvider');return c};
const emit=()=>{if(typeof window!=='undefined')window.dispatchEvent(new Event('pmm-auth-changed'))};
export const AuthProvider:React.FC<{children:React.ReactNode}>=({children})=>{const[user,setUser]=useState<AuthUser|null>(null);const[loading,setLoading]=useState(true);
const refresh=useCallback(async()=>{try{const r=await fetch('/api/auth/profile',{credentials:'include',cache:'no-store'});if(!r.ok){setUser(null);return null}const j=await r.json();setUser(j.user||null);return j.user as AuthUser|null}catch{setUser(null);return null}},[]);
useEffect(()=>{refresh().finally(()=>setLoading(false))},[refresh]);
const login=useCallback(async(identifier:string,password:string):Promise<LoginResult>=>{try{const rr=await fetch('/api/auth/resolve',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({identifier})});const resolved=await rr.json().catch(()=>({}));if(!rr.ok)return{success:false,error:resolved.error||'Identifiant introuvable.'};const result=await (authClient as any).signIn.email({email:resolved.email,password});if(result?.error)return{success:false,error:result.error.message||'Identifiant ou mot de passe incorrect.'};const appUser=await refresh();if(!appUser)return{success:false,error:'Compte authentifié mais profil PMM indisponible.'};emit();return{success:true}}catch(e:any){return{success:false,error:e?.message||'Erreur de connexion.'}}},[refresh]);
const logout=useCallback(async()=>{try{await (authClient as any).signOut()}finally{setUser(null);emit()}},[]);
const createUserWithRole=useCallback(async(email:string,password:string,role:UserRole,profileData:{id:string;name:string;[key:string]:any})=>{try{const r=await fetch('/api/admin/users',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password,role,profileData})});const j=await r.json().catch(()=>({}));if(!r.ok)return{success:false,error:j.error||'Création impossible.'};emit();return{success:true}}catch(e:any){return{success:false,error:e.message||'Création impossible.'}}},[]);
const migrateModelToAuth=useCallback(async()=>({success:false,error:'Ce portail utilise désormais Neon Auth. Les comptes mannequins ont déjà été centralisés.'}),[]);
const resetPassword=useCallback(async(email:string)=>{try{const r=await fetch('/api/auth/forget-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:email.trim().toLowerCase(),redirectTo:`${window.location.origin}/login`})});if(!r.ok){const j=await r.json().catch(()=>({}));return{success:false,error:j?.message||j?.error?.message||"Impossible d'envoyer le lien."}}return{success:true}}catch(e:any){return{success:false,error:e.message||"Impossible d'envoyer le lien."}}},[]);
const signInWithPhone=useCallback(async()=>({success:false,error:'La connexion par téléphone est désactivée.'}),[]);const confirmPhoneCode=useCallback(async()=>({success:false,error:'La connexion par téléphone est désactivée.'}),[]);
return <AuthContext.Provider value={{user,loading,login,logout,createUserWithRole,migrateModelToAuth,resetPassword,signInWithPhone,confirmPhoneCode}}>{children}</AuthContext.Provider>};
