import type { Article } from '../types';

/** Editorial additions that remain available alongside remotely managed CMS articles. */
export const magazineAdditions: Article[] = [
  {
    slug: 'shon-logan-mbazoghe-oniane-gabon-ambassadrice-environnement-lome-2026',
    title: "Shon Logan MBAZOGHE ONIANE : le Gabon brillera à la finale internationale d’Ambassadrice de l’Environnement",
    category: 'Actualités · Portrait · International',
    excerpt:
      "Le Gabon compte deux représentantes parmi les finalistes de la 6e édition d’Ambassadrice Internationale de l’Environnement – Vision Planète Verte. Parmi elles, Leila Shon Logan MBAZOGHE ONIANE portera les couleurs du Gabon à Lomé, au Togo, le 10 octobre 2026.",
    imageUrl: '',
    author: 'Perfect Models Management',
    date: '2026-08-21',
    status: 'published',
    isFeatured: true,
    tags: [
      'Gabon',
      'Shon Logan MBAZOGHE ONIANE',
      'Ambassadrice Internationale de l’Environnement',
      'Vision Planète Verte',
      'Environnement',
      'Leadership féminin',
      'Jeunesse',
      'Lomé',
      'International',
    ],
    reactions: { likes: 0, dislikes: 0 },
    viewCount: 0,
    content: [
      { type: 'paragraph', text: 'Le Gabon compte deux représentantes parmi les finalistes de la 6e édition d’Ambassadrice Internationale de l’Environnement – Vision Planète Verte. Parmi elles, Leila Shon Logan MBAZOGHE ONIANE portera les couleurs du Gabon à Lomé, au Togo, le 10 octobre 2026.' },
      { type: 'paragraph', text: 'Catégorie : Actualités · Portrait · International\nPays : Gabon 🇬🇦\nÉvénement : Ambassadrice Internationale de l’Environnement – Vision Planète Verte\nFinale : 10 octobre 2026 · 20h00 · Lomé, Togo' },
      { type: 'heading', level: 2, text: 'Qui est Shon Logan MBAZOGHE ONIANE ?' },
      { type: 'paragraph', text: 'Connue sous le nom de Shon Logan MBAZOGHE ONIANE, la candidate apparaît dans les documents officiels sous le nom complet MBAZOGHE ONIANE Leila Shon Logan.' },
      { type: 'paragraph', text: 'Elle fait partie des deux jeunes Gabonaises sélectionnées pour représenter le pays lors de la finale internationale de la 6e édition du concours Ambassadrice Internationale de l’Environnement – Vision Planète Verte.' },
      { type: 'paragraph', text: 'La présence de deux candidates gabonaises dans cette sélection constitue un signal fort pour le pays et pour une jeunesse qui entend associer représentation, engagement et responsabilité environnementale.' },
      { type: 'heading', level: 2, text: 'Une représentante d’une jeunesse gabonaise engagée' },
      { type: 'paragraph', text: 'Au-delà de l’image et de la représentation, le concours met en avant des jeunes femmes capables de porter une vision et de défendre des initiatives concrètes en faveur de l’environnement.' },
      { type: 'paragraph', text: 'Shon Logan s’inscrit ainsi dans une génération pour laquelle la protection de la nature, la sensibilisation du public et la responsabilité collective deviennent des enjeux majeurs.' },
      { type: 'paragraph', text: 'Son parcours vers Lomé intervient également dans un contexte où le Gabon cherche à renforcer son image de pays engagé dans la préservation de ses écosystèmes et de la forêt du bassin du Congo.' },
      { type: 'heading', level: 2, text: 'Vision Planète Verte : bien plus qu’un concours de beauté' },
      { type: 'paragraph', text: 'L’Ambassadrice Internationale de l’Environnement – Vision Planète Verte se présente comme un programme qui associe représentation, leadership féminin et engagement environnemental.' },
      { type: 'paragraph', text: 'Le programme officiel met notamment en avant la jeunesse, les femmes, le climat, les actions citoyennes et les projets environnementaux. Ses activités s’articulent autour de l’actualité, du terrain, des projets, de l’éducation, de l’impact et de l’international.' },
      { type: 'paragraph', text: 'L’objectif est donc de faire de la candidate une véritable porte-parole d’une cause, plutôt qu’une simple détentrice d’un titre.' },
      { type: 'heading', level: 2, text: '20 finalistes pour une grande finale panafricaine' },
      { type: 'paragraph', text: 'La 6e édition rassemble des candidates issues de plusieurs pays africains. La liste officielle publiée par l’organisation présente notamment deux représentantes du Gabon : MBEMBO KOUMBA Tressy et MBAZOGHE ONIANE Leila Shon Logan.' },
      { type: 'paragraph', text: 'Bénin : AGOSSOU Marie-Thérèse\nCôte d’Ivoire : KOUASSI Amani Grâce, PLEYA Popa Grace Dominique Ange\nGabon : MBEMBO KOUMBA Tressy, MBAZOGHE ONIANE Leila Shon Logan\nGuinée-Conakry : BAH Kadiatou Bailo, BOEDOUNO Koumba Cécile, THEA Germaine\nMali : CISSE Mariam, DEMBELE Fatoumata, TOURE Aichata\nSénégal : CISSE Ndeye Marienne\nTchad : NOUEMEM NAKIRI Nicaise\nTogo : AMAVI Essi Justine, AKPAKA Yawa Victoire, BOUKPESSI Magnim Ninon, DZOKA Yawa Bérénice, JOHNSON Afereba Claudia, N’BALIBA Djete Gloria, SEMEGLO Ami Anita' },
      { type: 'heading', level: 2, text: 'Rendez-vous le 10 octobre à Lomé' },
      { type: 'paragraph', text: 'La grande finale internationale est annoncée pour le samedi 10 octobre 2026 à 20h00 à Lomé, au Togo. L’organisation a publié un Save the Date officiel pour cette échéance.' },
      { type: 'paragraph', text: 'La compétition prendra place dans la capitale togolaise, pays hôte de cette édition. À l’approche de cette échéance, les candidates sont appelées à poursuivre leur préparation et leur engagement autour des enjeux environnementaux.' },
      { type: 'heading', level: 2, text: 'L’environnement au cœur de la compétition' },
      { type: 'paragraph', text: 'L’une des particularités du programme réside dans la place accordée aux actions environnementales. Le site officiel de l’organisation présente notamment des initiatives liées à la reforestation, l’éducation environnementale, la sensibilisation citoyenne, la réduction des déchets et l’engagement communautaire.' },
      { type: 'paragraph', text: 'Cette orientation donne au titre une dimension particulière : la future ambassadrice doit pouvoir utiliser sa visibilité pour défendre des causes et encourager des actions concrètes.' },
      { type: 'heading', level: 2, text: 'Quels enjeux pour Shon Logan ?' },
      { type: 'paragraph', text: 'Pour la représentante gabonaise, cette finale constitue une opportunité de visibilité internationale. Elle pourra porter plusieurs messages : la place de la jeunesse gabonaise dans les enjeux climatiques ; la protection de l’environnement ; la valorisation de l’image du Gabon ; la participation des jeunes femmes aux initiatives citoyennes ; et la nécessité de transformer la sensibilisation en actions concrètes.' },
      { type: 'paragraph', text: 'Pour le Gabon, cette participation dépasse donc le cadre d’un concours. Elle constitue une occasion supplémentaire de mettre en avant un pays dont l’identité environnementale est étroitement liée à la richesse de ses forêts et de sa biodiversité.' },
      { type: 'heading', level: 2, text: 'Le Gabon derrière ses représentantes 🇬🇦' },
      { type: 'paragraph', text: 'Avec MBEMBO KOUMBA Tressy et MBAZOGHE ONIANE Leila Shon Logan, le Gabon dispose de deux représentantes pour cette sixième édition. La mobilisation autour de leur participation devrait désormais s’intensifier à mesure que la finale approche.' },
      { type: 'paragraph', text: '🇬🇦 GABON → 🇹🇬 LOMÉ\n10 octobre 2026 · 20h00\nToute une nation pourra suivre ses représentantes et les encourager dans cette aventure panafricaine.' },
      { type: 'heading', level: 2, text: 'Comment suivre le concours ?' },
      { type: 'paragraph', text: 'Le site officiel de l’organisation publie les actualités et les différentes étapes de la compétition. Coordonnées officielles : +228 99 51 49 29 · environnementambassadrice@gmail.com.' },
      { type: 'paragraph', text: 'Source officielle : https://www.ambassadriceenvironnement.org/' },
      { type: 'heading', level: 2, text: '🇬🇦 Shon Logan, une voix du Gabon à Lomé' },
      { type: 'paragraph', text: 'Le 10 octobre prochain, les regards se tourneront vers Lomé. Derrière la couronne et les projecteurs, c’est aussi une histoire de représentation, d’engagement et de responsabilité qui se jouera.' },
      { type: 'paragraph', text: 'Pour Shon Logan MBAZOGHE ONIANE, cette finale internationale sera l’occasion de faire entendre une voix gabonaise et de porter, au-delà des frontières, l’image d’une jeunesse qui veut participer pleinement à la construction d’un avenir plus durable.' },
      { type: 'paragraph', text: 'Le Gabon sera à Lomé. Et il aura deux représentantes pour défendre ses couleurs. 🇬🇦' },
    ],
  },
];
