'use client';

import { useState } from 'react';
import Link from 'next/link';
import { ArrowRight, CheckCircle2, Loader2 } from 'lucide-react';

type RequestRow = { id: string; name: string | null; email: string | null; phone: string | null; model_id: string | null; status: string; raw_data: Record<string, any> | null; modelName?: string | null };

export default function BookingRequestQueue({ initialRows }: { initialRows: RequestRow[] }) {
  const [rows, setRows] = useState(initialRows); const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const convert = async (row: RequestRow) => { setBusy(row.id); setError(''); setNotice(''); try { const response = await fetch(`/api/admin/booking-requests/${row.id}/convert`, { method: 'POST', credentials: 'include' }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(result.error || 'Conversion impossible.'); setRows((current) => current.filter((item) => item.id !== row.id)); setNotice('La demande est devenue un booking de production avec son option initiale.'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Conversion impossible.'); } finally { setBusy(''); } };
  return <section className="control-card mb-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="control-kicker">Intake → Production</p><h2 className="mt-2 font-playfair text-3xl font-semibold">Demandes à qualifier</h2><p className="mt-2 max-w-2xl text-sm text-pm-ink/50">Une demande publique reste un lead jusqu’à sa conversion. La conversion crée le client si nécessaire, le booking et l’Option 1.</p></div><Link href="/admin/bookings" className="rounded-full border border-pm-ink/10 px-4 py-2 text-xs font-bold">Voir les bookings</Link></div>{notice && <p className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm font-semibold text-emerald-800">{notice}</p>}{error && <p role="alert" className="mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-semibold text-red-800">{error}</p>}<div className="mt-5 grid gap-3">{rows.map((row) => { const raw = row.raw_data || {}; return <article key={row.id} className="grid gap-4 rounded-2xl border border-pm-ink/10 bg-pm-ivory p-4 lg:grid-cols-[1fr_auto] lg:items-center"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-playfair text-2xl font-bold">{raw.clientCompany || row.name || 'Demande client'}</h3><span className="rounded-full bg-white px-2.5 py-1 text-[9px] font-black uppercase text-pm-wine">{row.status}</span></div><p className="mt-1 text-sm text-pm-ink/55">{[row.name,row.email,row.modelName || row.model_id].filter(Boolean).join(' · ')}</p><p className="mt-2 text-xs text-pm-ink/45">{[raw.projectType,raw.startDate,raw.endDate].filter(Boolean).join(' · ')}</p></div><button type="button" disabled={busy === row.id || !row.model_id} onClick={() => void convert(row)} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-full bg-pm-ink px-5 text-xs font-black uppercase tracking-[.08em] text-white disabled:cursor-not-allowed disabled:opacity-40">{busy === row.id ? <Loader2 size={15} className="animate-spin"/> : row.model_id ? <ArrowRight size={15}/> : <CheckCircle2 size={15}/>} {row.model_id ? 'Convertir en booking' : 'Mannequin requis'}</button></article>; })}{!rows.length && <p className="rounded-2xl bg-pm-ivory p-6 text-center text-sm text-pm-ink/45">Aucune demande non convertie à traiter.</p>}</div></section>;
}
