import{useCallback,useEffect,useState}from'react';import logger from'../utils/logger';import{invalidateCache}from'./useFirebaseCollection';import{navLinks as initialNavLinks}from'../constants/data';import type{Model,FashionDayEvent,Service,AchievementCategory,ModelDistinction,Testimonial,ContactInfo,SiteImages,Partner,ApiKeys,CastingApplication,FashionDayApplication,NewsItem,ForumThread,ForumReply,Article,Module,ArticleComment,RecoveryRequest,JuryMember,RegistrationStaff,BookingRequest,ContactMessage,FAQCategory,Absence,MonthlyPayment,Transaction,PhotoshootBrief,NavLink,AdminProfile,GalleryItem,GalleryAlbum,MailingContact}from'../types';
export const LAZY_COLLECTIONS=['castingApplications','fashionDayApplications','contactMessages','bookingRequests','recoveryRequests','articleComments','forumReplies','absences','monthlyPayments','transactions','photoshootBriefs','mailingContacts','gallery','galleryAlbums']as const;
export interface AppData{siteConfig:{logo:string};navLinks:NavLink[];socialLinks:{facebook:string;instagram:string;youtube:string};agencyTimeline:{year:string;event:string}[];agencyInfo:{about:{p1:string;p2:string};values:{name:string;description:string}[]};modelDistinctions:ModelDistinction[];agencyServices:Service[];agencyAchievements:AchievementCategory[];agencyPartners:Partner[];models:Model[];fashionDayEvents:FashionDayEvent[];testimonials:Testimonial[];articles:Article[];courseData:Module[];contactInfo:ContactInfo;siteImages:SiteImages;apiKeys:ApiKeys;castingApplications:CastingApplication[];fashionDayApplications:FashionDayApplication[];newsItems:NewsItem[];forumThreads:ForumThread[];forumReplies:ForumReply[];articleComments:ArticleComment[];recoveryRequests:RecoveryRequest[];bookingRequests:BookingRequest[];contactMessages:ContactMessage[];juryMembers:JuryMember[];registrationStaff:RegistrationStaff[];faqData:FAQCategory[];absences:Absence[];monthlyPayments:MonthlyPayment[];transactions:Transaction[];photoshootBriefs:PhotoshootBrief[];adminProfile:AdminProfile;gallery:GalleryItem[];galleryAlbums:GalleryAlbum[];mailingContacts:MailingContact[];[key:string]:any}
const arr=(v:any)=>Array.isArray(v)?v.filter(Boolean):v&&typeof v==='object'?Object.values(v).filter(Boolean):[];const dedupe=(a:any[])=>{const s=new Set<string>();return a.filter(i=>{const k=String(i?.id??JSON.stringify(i));if(s.has(k))return false;s.add(k);return true})};
const MEDIA_REPLACEMENTS:Record<string,string>={
'https://i.ibb.co/K2wS0Pz/hero-bg.jpg':'https://i.ibb.co/276ywtCY/1005986095.jpg',
'https://i.ibb.co/3WfK9Xg/about-img.jpg':'https://i.ibb.co/Y7fwZSpq/1005663576.jpg',
'https://i.ibb.co/C5rcPJHz/titostyle-53.jpg':'https://i.ibb.co/pp4JkH0/1006010669.jpg',
'https://i.ibb.co/jH0YvJg/agency-history.jpg':'https://i.ibb.co/Q7SzHjM3/IMG-4642.jpg',
'https://i.ibb.co/TBt9FBSv/AJC-4630.jpg':'https://i.ibb.co/5h5nr12w/1000014518.jpg',
'https://i.ibb.co/z5TzL2M/casting-bg.jpg':'https://i.ibb.co/fd8nGq3D/MG-0658-Modifier.jpg',
'https://i.ibb.co/Pzm6kdQ/559155589-797412703143073-47429732447466306-n.jpg':'https://i.ibb.co/kgdYYP5b/559155589-797412703143073-47429732447466306-n.jpg',
'https://i.ibb.co/RpXtWzq/1005252341.png':'/opengraph-image',
};
const repairMedia=(value:any):any=>{if(typeof value==='string')return MEDIA_REPLACEMENTS[value]||value;if(Array.isArray(value))return value.map(repairMedia);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([key,item])=>[key,repairMedia(item)]));return value};
export const useRealtimeDB=()=>{const[data,setData]=useState<AppData|null>(null);const[isInitialized,setInitialized]=useState(false);
const seed=useCallback(async():Promise<AppData>=>{const[{articles},{courseData},d]=await Promise.all([import('../constants/magazineData'),import('../constants/courseData'),import('../constants/data')]);return repairMedia({...d,articles,courseData,transactions:[],gallery:[],galleryAlbums:[],adminProfile:{id:'admin',name:'Administration PMM',username:'admin',password:'',email:'admin@perfectmodels.online'}})as unknown as AppData},[]);
const normalize=useCallback(async(raw:any)=>{const initial=await seed();const merged:any={...initial,...raw,apiKeys:initial.apiKeys};for(const key of LAZY_COLLECTIONS)if(!Array.isArray(merged[key]))merged[key]=arr(merged[key]);for(const key of['models','agencyPartners','agencyServices','agencyAchievements','modelDistinctions','testimonials','articles','courseData','newsItems','forumThreads','juryMembers','registrationStaff','faqData','mailingContacts'])merged[key]=dedupe(arr(merged[key]));merged.navLinks=dedupe([...arr(raw?.navLinks),...initialNavLinks.filter(n=>!arr(raw?.navLinks).some((x:any)=>x?.path===n.path))]).filter((l:any)=>l?.path!=='/'&&l?.path!=='/fashion-day');merged.fashionDayEvents=dedupe(arr(merged.fashionDayEvents));return repairMedia(merged) as AppData},[seed]);
const load=useCallback(async()=>{try{const r=await fetch('/api/data',{credentials:'include',cache:'no-store'});if(!r.ok)throw new Error(`API data ${r.status}`);const j=await r.json();setData(await normalize(j.data||{}))}catch(e){logger.error('Neon data load failed',e);setData(await seed())}finally{setInitialized(true)}},[normalize,seed]);
useEffect(()=>{load();const h=()=>load();window.addEventListener('pmm-auth-changed',h);return()=>window.removeEventListener('pmm-auth-changed',h)},[load]);
const saveData=useCallback(async(newData:AppData)=>{const r=await fetch('/api/data',{method:'PUT',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(newData)});if(!r.ok){const j=await r.json().catch(()=>({}));throw new Error(j.error||'Sauvegarde Neon impossible')}setData(newData);LAZY_COLLECTIONS.forEach(invalidateCache)},[]);
const addDocument=useCallback(async(path:string,item:any)=>{const r=await fetch(`/api/data/${encodeURIComponent(path)}`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(item)});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Création impossible');invalidateCache(path);await load();return j.id as string},[load]);
const updateDocument=useCallback(async(path:string,id:string,updates:any)=>{const r=await fetch(`/api/data/${encodeURIComponent(path)}/${encodeURIComponent(id)}`,{method:'PATCH',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(updates)});if(!r.ok)throw new Error('Mise à jour impossible');invalidateCache(path);await load()},[load]);
const deleteDocument=useCallback(async(path:string,id:string)=>{const r=await fetch(`/api/data/${encodeURIComponent(path)}/${encodeURIComponent(id)}`,{method:'DELETE',credentials:'include'});if(!r.ok)throw new Error('Suppression impossible');invalidateCache(path);await load()},[load]);
return{data,saveData,isInitialized,addDocument,updateDocument,deleteDocument}};
