'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';

export default function JuryScoreForm({applicationId,initial}:{applicationId:string;initial?:Record<string,any>|null}){
  const router=useRouter();const[state,setState]=useState({physique:Number(initial?.physique||0),presence:Number(initial?.presence||0),photogenie:Number(initial?.photogenie||0),potentiel:Number(initial?.potentiel||0),notes:String(initial?.notes||'')});const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[done,setDone]=useState(false);
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');setDone(false);try{const r=await fetch('/api/jury/casting-scores',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({castingApplicationId:applicationId,...state})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Notation impossible');setDone(true);router.refresh()}catch(err){setError(err instanceof Error?err.message:'Notation impossible')}finally{setBusy(false)}};
  return <form onSubmit={submit} className="mt-5 border-t border-white/10 pt-5"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{(['physique','presence','photogenie','potentiel'] as const).map(key=><label key={key} className="text-[8px] font-bold uppercase tracking-wider text-white/35">{key}<input type="number" min="0" max="10" step="0.5" value={state[key]} onChange={e=>setState(s=>({...s,[key]:Number(e.target.value)}))} className="mt-2 w-full border border-white/10 bg-black/30 px-3 py-2 text-sm text-white"/></label>)}</div><textarea value={state.notes} onChange={e=>setState(s=>({...s,notes:e.target.value}))} placeholder="Notes du jury" className="mt-3 min-h-20 w-full border border-white/10 bg-black/30 px-3 py-2 text-sm"/>{error&&<p className="mt-2 text-xs text-red-300">{error}</p>}{done&&<p className="mt-2 text-xs text-pm-gold">Note enregistrée.</p>}<button disabled={busy} className="mt-3 bg-pm-gold px-4 py-2 text-[8px] font-black uppercase tracking-wider text-black">Enregistrer la note</button></form>;
}
