import { redirect } from 'next/navigation';
import { getCurrentAppProfile } from '@/lib/auth/profile';
import { createSupabaseAdminClient } from '@/lib/supabase/admin';

export const dynamic = 'force-dynamic';
const money=(value:number)=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'XAF',maximumFractionDigits:0}).format(value||0);

export default async function AnalyticsPage(){
 const profile=await getCurrentAppProfile(); if(!profile) redirect('/login?next=/admin/analytics'); if(profile.role!=='admin') redirect(profile.role==='manager'?'/manager':'/profil');
 const supabase=createSupabaseAdminClient() as any;
 const [{data:bookings},{data:castingTalents},{data:models},{data:clients},{data:invoices}]=await Promise.all([
  supabase.from('bookings').select('id,model_id,client_id,status,fee_gross,agency_commission_amount,starts_at').neq('status','cancelled'),
  supabase.from('casting_talents').select('model_id,casting_id,stage,match_score'),
  supabase.from('models').select('id,name').eq('is_active',true),
  supabase.from('agency_clients').select('id,name,status'),
  supabase.from('invoices').select('client_id,total,amount_paid,status,issued_at,due_at'),
 ]);
 const modelNames=new Map((models||[]).map((row:any)=>[String(row.id),String(row.name)])); const clientNames=new Map((clients||[]).map((row:any)=>[String(row.id),String(row.name)]));
 const talentStats=new Map<string,{bookings:number,revenue:number,requests:number}>();
 for(const row of bookings||[]){const key=String(row.model_id);const s=talentStats.get(key)||{bookings:0,revenue:0,requests:0};s.bookings++;s.revenue+=Number(row.fee_gross||0);talentStats.set(key,s)}
 for(const row of castingTalents||[]){const key=String(row.model_id);const s=talentStats.get(key)||{bookings:0,revenue:0,requests:0};s.requests++;talentStats.set(key,s)}
 const topTalents=[...talentStats.entries()].map(([id,s])=>({id,name:modelNames.get(id)||id,...s})).sort((a,b)=>b.bookings-a.bookings||b.revenue-a.revenue).slice(0,8);
 const clientStats=new Map<string,{bookings:number,revenue:number,outstanding:number}>();
 for(const row of bookings||[]){if(!row.client_id)continue;const key=String(row.client_id);const s=clientStats.get(key)||{bookings:0,revenue:0,outstanding:0};s.bookings++;s.revenue+=Number(row.fee_gross||0);clientStats.set(key,s)}
 for(const row of invoices||[]){if(!row.client_id)continue;const key=String(row.client_id);const s=clientStats.get(key)||{bookings:0,revenue:0,outstanding:0};s.outstanding+=Math.max(0,Number(row.total||0)-Number(row.amount_paid||0));clientStats.set(key,s)}
 const topClients=[...clientStats.entries()].map(([id,s])=>({id,name:clientNames.get(id)||id,...s})).sort((a,b)=>b.revenue-a.revenue).slice(0,8);
 const stages=(castingTalents||[]).reduce((acc:Record<string,number>,row:any)=>{acc[row.stage]=(acc[row.stage]||0)+1;return acc},{});
 const invitations=(castingTalents||[]).length; const attended=(stages.attended||0)+(stages.shortlist||0)+(stages.callback||0)+(stages.selected||0)+(stages.booked||0); const shortlisted=(stages.shortlist||0)+(stages.callback||0)+(stages.selected||0)+(stages.booked||0); const booked=stages.booked||0; const conversion=invitations?Math.round(booked/invitations*1000)/10:0;
 const totalRevenue=(bookings||[]).reduce((s:number,row:any)=>s+Number(row.fee_gross||0),0); const totalCommission=(bookings||[]).reduce((s:number,row:any)=>s+Number(row.agency_commission_amount||0),0); const avgBooking=(bookings||[]).length?Math.round(totalRevenue/(bookings||[]).length):0;
 const utilizationModels=new Set((bookings||[]).filter((row:any)=>['confirmed','in_production','completed'].includes(row.status)).map((row:any)=>String(row.model_id))).size; const utilization=(models||[]).length?Math.round(utilizationModels/(models||[]).length*1000)/10:0;
 return <div className="space-y-6 pb-12"><header className="rounded-[2rem] bg-pm-wine p-7 text-white sm:p-9"><p className="text-[10px] font-black uppercase tracking-[.2em] text-pm-gold-light">Analytics agence</p><h1 className="mt-3 font-playfair text-5xl font-semibold">Mesurer ce qui transforme un talent en revenu.</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-white/65">Les indicateurs sont calculés uniquement à partir des castings, bookings, clients et factures réellement enregistrés.</p></header><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[['Revenu',money(totalRevenue)],['Commission',money(totalCommission)],['Booking moyen',money(avgBooking)],['Conversion casting',`${conversion}%`],['Utilisation talents',`${utilization}%`]].map(([label,value])=><div key={label} className="control-card"><p className="control-kicker">{label}</p><p className="mt-5 font-playfair text-3xl font-semibold">{value}</p></div>)}</section>
 <section className="grid gap-5 lg:grid-cols-2"><Table title="Talents les plus performants" headers={['Talent','Bookings','Demandes','CA']} rows={topTalents.map((row)=>[row.name,String(row.bookings),String(row.requests),money(row.revenue)])}/><Table title="Clients les plus actifs" headers={['Client','Bookings','CA','À encaisser']} rows={topClients.map((row)=>[row.name,String(row.bookings),money(row.revenue),money(row.outstanding)])}/></section>
 <section className="control-card"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="control-kicker">Conversion casting</p><h2 className="mt-2 font-playfair text-3xl font-semibold">Du premier contact au booking</h2></div><strong className="font-playfair text-4xl text-pm-wine">{conversion}%</strong></div><div className="mt-7 grid gap-3 md:grid-cols-4">{[['Invitations',invitations],['Casting effectué',attended],['Shortlist',shortlisted],['Booké',booked]].map(([label,value],index)=><div key={label as string} className="rounded-2xl bg-pm-ivory p-4"><p className="text-[9px] font-black uppercase tracking-[.12em] text-pm-coral">0{index+1}</p><p className="mt-3 font-playfair text-4xl font-semibold">{value}</p><p className="mt-1 text-xs text-pm-ink/45">{label}</p><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-pm-ink/10"><div className="h-full rounded-full bg-pm-coral" style={{width:`${invitations?Math.max(3,Number(value)/invitations*100):0}%`}}/></div></div>)}</div></section></div>;
}
function Table({title,headers,rows}:{title:string;headers:string[];rows:string[][]}){return <section className="control-card overflow-hidden"><h2 className="font-playfair text-2xl font-semibold">{title}</h2><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[480px] text-left text-sm"><thead><tr className="border-b border-pm-ink/10 text-[9px] font-black uppercase tracking-[.1em] text-pm-ink/40">{headers.map(h=><th key={h} className="px-2 py-3">{h}</th>)}</tr></thead><tbody>{rows.length?rows.map((row,i)=><tr key={i} className="border-b border-pm-ink/[.06] last:border-0">{row.map((cell,j)=><td key={j} className={`px-2 py-3 ${j===0?'font-bold':''}`}>{cell}</td>)}</tr>):<tr><td colSpan={headers.length} className="py-8 text-center text-pm-ink/40">Aucune donnée métier disponible pour le moment.</td></tr>}</tbody></table></div></section>}
