// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjluydkyuhrhnlsewdsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqbHV5ZGt5dWhyaG5sc2V3ZHNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MTU4MzksImV4cCI6MjA2MzQ5MTgzOX0._BKw6702XEXbpelj4hmQNhJxlOOvU5PeBvrQOuUA4_s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);