export interface DatabaseReference{path:string;key:string|null}export type Query=DatabaseReference;export type Database=Record<string,never>;
const clean=(p='')=>p.replace(/^\/+|\/+$/g,'');const url=(p:string)=>p?`/api/data/${p.split('/').map(encodeURIComponent).join('/')}`:'/api/data';
export const getDatabase=()=>({});export function ref(_db?:unknown,p=''){const path=clean(p),parts=path.split('/');return{path,key:path?parts[parts.length-1]||null:null}}export const child=(r:DatabaseReference,p:string)=>ref(null,[r.path,clean(p)].filter(Boolean).join('/'));export function push(r:DatabaseReference,v?:unknown):any{const n=child(r,crypto.randomUUID());if(v!==undefined)return set(n,v).then(()=>n);return n}
export class DataSnapshot{constructor(private value:any,public key:string|null=null){}val(){return this.value}exists(){return this.value!==null&&this.value!==undefined}forEach(cb:(s:DataSnapshot)=>boolean|void){if(!this.value||typeof this.value!=='object')return false;for(const[k,v]of Object.entries(this.value))if(cb(new DataSnapshot(v,k))===true)return true;return false}}
export async function get(r:DatabaseReference){const res=await fetch(url(r.path),{credentials:'include',cache:'no-store'});if(!res.ok)throw new Error(`Lecture impossible (${res.status})`);return new DataSnapshot(await res.json(),r.key)}
export async function set(r:DatabaseReference,v:unknown){const res=await fetch(url(r.path),{method:'PUT',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(v)});if(!res.ok)throw new Error((await res.json().catch(()=>({})))?.error||'Écriture impossible')}
export async function update(r:DatabaseReference,v:Record<string,unknown>){const res=await fetch(url(r.path),{method:'PATCH',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(v)});if(!res.ok)throw new Error((await res.json().catch(()=>({})))?.error||'Mise à jour impossible')}
export async function remove(r:DatabaseReference){const res=await fetch(url(r.path),{method:'DELETE',credentials:'include'});if(!res.ok)throw new Error((await res.json().catch(()=>({})))?.error||'Suppression impossible')}
export function onValue(r:DatabaseReference,cb:(s:DataSnapshot)=>void,onError?:(e:Error)=>void){let active=true;const load=()=>get(r).then(s=>{if(active)cb(s)}).catch(e=>onError?.(e));load();const id=typeof window!=='undefined'?window.setInterval(load,15000):0;return()=>{active=false;if(id)clearInterval(id)}}
export const query=(r:DatabaseReference,..._c:unknown[])=>r;export const orderByChild=(value:string)=>({type:'orderByChild',value});export const orderByKey=()=>({type:'orderByKey'});export const limitToLast=(value:number)=>({type:'limitToLast',value});export const limitToFirst=(value:number)=>({type:'limitToFirst',value});export const equalTo=(value:unknown)=>({type:'equalTo',value});export const startAt=(value:unknown)=>({type:'startAt',value});export const endAt=(value:unknown)=>({type:'endAt',value});export const serverTimestamp=()=>new Date().toISOString();export const increment=(delta:number)=>({__increment:delta});
export async function runTransaction(r:DatabaseReference,fn:(v:any)=>any){const before=await get(r);const next=fn(before.val());if(next===undefined)return{committed:false,snapshot:before};await set(r,next);return{committed:true,snapshot:new DataSnapshot(next,r.key)}}
