export type Firestore=Record<string,never>;export interface DocumentReference{path:string;id:string}export interface CollectionReference{path:string}export const getFirestore=()=>({});export const collection=(_db:unknown,...p:string[])=>({path:p.join('/')});export const doc=(_dbOrCol:any,...p:string[])=>{const prefix=_dbOrCol?.path?`${_dbOrCol.path}/`:'';const path=prefix+p.join('/');return{path,id:path.split('/').at(-1)||''}};
class Snap{constructor(private dataValue:any,public id=''){}exists(){return this.dataValue!=null}data(){return this.dataValue}}
export async function getDoc(r:DocumentReference){const res=await fetch(`/api/compat/doc?path=${encodeURIComponent(r.path)}`,{credentials:'include',cache:'no-store'});if(!res.ok)return new Snap(null,r.id);const j=await res.json();return new Snap(j.data,r.id)}
export async function setDoc(r:DocumentReference,data:any,opts?:{merge?:boolean}){const res=await fetch('/api/compat/doc',{method:'PUT',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:r.path,data,merge:Boolean(opts?.merge)})});if(!res.ok)throw new Error('Écriture document impossible')}
export const updateDoc=(r:DocumentReference,data:any)=>setDoc(r,data,{merge:true});export async function deleteDoc(r:DocumentReference){await fetch(`/api/compat/doc?path=${encodeURIComponent(r.path)}`,{method:'DELETE',credentials:'include'})}export const serverTimestamp=()=>new Date().toISOString();export const Timestamp={now:()=>new Date()};export const increment=(n:number)=>({__increment:n});export const arrayUnion=(...v:unknown[])=>v;export const arrayRemove=(...v:unknown[])=>v;
export const where=(...args:unknown[])=>({type:'where',args});export const orderBy=(...args:unknown[])=>({type:'orderBy',args});export const limit=(n:number)=>({type:'limit',n});export const query=(c:any,...constraints:any[])=>({...c,constraints});
export async function getDocs(c:any){const res=await fetch(`/api/data/${encodeURIComponent(c.path)}`,{credentials:'include',cache:'no-store'});const raw=res.ok?await res.json():[];const arr=Array.isArray(raw)?raw:Object.entries(raw||{}).map(([id,v])=>({...(v as any),id}));return{docs:arr.map((v:any)=>new Snap(v,v.id||'')),empty:!arr.length,size:arr.length,forEach:(cb:any)=>arr.forEach((v:any)=>cb(new Snap(v,v.id||'')))}}
export async function addDoc(c:CollectionReference,data:any){const res=await fetch(`/api/data/${encodeURIComponent(c.path)}`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const j=await res.json();return{path:`${c.path}/${j.id}`,id:j.id}}
export function onSnapshot(q:any,cb:(s:any)=>void){let active=true;const load=()=>getDocs(q).then(s=>active&&cb(s)).catch(()=>{});load();const id=typeof window!=='undefined'?window.setInterval(load,15000):0;return()=>{active=false;if(id)clearInterval(id)}}
export function writeBatch(_db?:unknown){const ops:Array<()=>Promise<any>>=[];return{set:(r:any,d:any,o?:any)=>{ops.push(()=>setDoc(r,d,o));return this},update:(r:any,d:any)=>{ops.push(()=>updateDoc(r,d));return this},delete:(r:any)=>{ops.push(()=>deleteDoc(r));return this},commit:()=>Promise.all(ops.map(f=>f()))}}
