export type Firestore=Record<string,never>;export interface DocumentReference{path:string;id:string}export interface CollectionReference{path:string}export const getFirestore=()=>({});export const collection=(_db:unknown,...p:string[])=>({path:p.join('/')});export const doc=(_dbOrCol:any,...p:string[])=>{const prefix=_dbOrCol?.path?`${_dbOrCol.path}/`:'';const path=prefix+p.join('/'),parts=path.split('/');return{path,id:parts[parts.length-1]||''}};
const apiPath=(p:string)=>`/api/data/${p.split('/').map(encodeURIComponent).join('/')}`;
class Snap{constructor(private dataValue:any,public id=''){}exists(){return this.dataValue!=null}data(){return this.dataValue}}
export async function getDoc(r:DocumentReference){const res=await fetch(`/api/compat/doc?path=${encodeURIComponent(r.path)}`,{credentials:'include',cache:'no-store'});if(!res.ok)return new Snap(null,r.id);const j=await res.json();return new Snap(j.data,r.id)}
export async function setDoc(r:DocumentReference,data:any,opts?:{merge?:boolean}){const res=await fetch('/api/compat/doc',{method:'PUT',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:r.path,data,merge:Boolean(opts?.merge)})});if(!res.ok)throw new Error('Écriture document impossible')}
export const updateDoc=(r:DocumentReference,data:any)=>setDoc(r,data,{merge:true});export async function deleteDoc(r:DocumentReference){await fetch(`/api/compat/doc?path=${encodeURIComponent(r.path)}`,{method:'DELETE',credentials:'include'})}export const serverTimestamp=()=>new Date().toISOString();export class Timestamp{static now(){return new Timestamp(new Date())}constructor(public value:Date){}toDate(){return this.value}}export const increment=(n:number)=>({__increment:n});export const arrayUnion=(...v:unknown[])=>v;export const arrayRemove=(...v:unknown[])=>v;
export const where=(...args:unknown[])=>({type:'where',args});export const orderBy=(...args:unknown[])=>({type:'orderBy',args});export const limit=(n:number)=>({type:'limit',n});export const query=(c:any,...constraints:any[])=>({...c,constraints});
export async function getDocs(c:any){const res=await fetch(apiPath(c.path),{credentials:'include',cache:'no-store'});const raw=res.ok?await res.json():[];const arr=Array.isArray(raw)?raw:Object.entries(raw||{}).map(([id,v])=>({...(v as any),id}));const docs=arr.map((v:any)=>new Snap(v,v.id||''));return{docs,empty:!arr.length,size:arr.length,forEach:(cb:any)=>docs.forEach(cb)}}
export async function addDoc(c:CollectionReference,data:any){const res=await fetch(apiPath(c.path),{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const j=await res.json();return{path:`${c.path}/${j.id}`,id:j.id}}
export function onSnapshot(q:any,cb:(s:any)=>void){let active=true;const load=()=>getDocs(q).then(s=>active&&cb(s)).catch(()=>{});load();const id=typeof window!=='undefined'?window.setInterval(load,15000):0;return()=>{active=false;if(id)clearInterval(id)}}
export function writeBatch(_db?:unknown){const ops:Array<()=>Promise<any>>=[];const batch:any={set:(r:any,d:any,o?:any)=>{ops.push(()=>setDoc(r,d,o));return batch},update:(r:any,d:any)=>{ops.push(()=>updateDoc(r,d));return batch},delete:(r:any)=>{ops.push(()=>deleteDoc(r));return batch},commit:()=>Promise.all(ops.map(f=>f()))};return batch}
export async function runTransaction(_db:any,fn:(tx:any)=>Promise<any>){const tx={get:getDoc,set:setDoc,update:updateDoc,delete:deleteDoc};return fn(tx)}
